### ISSUE TITLE
Installation doesn't work in virtual environnement

### ISSUE THREAD

**Issue by gantsevdenis** [dalibo/pg_activity#121]
```
(py37) denis:~/gitdnwld/pg_activity $ python setup.py install
running install
running bdist_egg
running egg_info
writing pg_activity.egg-info/PKG-INFO
writing dependency_links to pg_activity.egg-info/dependency_links.txt
writing requirements to pg_activity.egg-info/requires.txt
writing top-level names to pg_activity.egg-info/top_level.txt
reading manifest file 'pg_activity.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 1: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'pg_activity.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pgactivity
copying build/lib/pgactivity/UI.py -> build/bdist.linux-x86_64/egg/pgactivity
copying build/lib/pgactivity/Data.py -> build/bdist.linux-x86_64/egg/pgactivity
copying build/lib/pgactivity/Process.py -> build/bdist.linux-x86_64/egg/pgactivity
copying build/lib/pgactivity/__init__.py -> build/bdist.linux-x86_64/egg/pgactivity
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/UI.py to UI.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/Data.py to Data.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/Process.py to Process.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/pg_activity -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/pg_activity to 775
copying pg_activity.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pg_activity-1.5.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pg_activity-1.5.0-py3.7.egg
Removing /home/denis/anaconda3/envs/py37/lib/python3.7/site-packages/pg_activity-1.5.0-py3.7.egg
Copying pg_activity-1.5.0-py3.7.egg to /home/denis/anaconda3/envs/py37/lib/python3.7/site-packages
pg-activity 1.5.0 is already the active version in easy-install.pth
Installing pg_activity script to /home/denis/anaconda3/envs/py37/bin

Installed /home/denis/anaconda3/envs/py37/lib/python3.7/site-packages/pg_activity-1.5.0-py3.7.egg
Processing dependencies for pg-activity==1.5.0
Searching for psycopg2==2.8.3
Best match: psycopg2 2.8.3
Adding psycopg2 2.8.3 to easy-install.pth file

Using /home/denis/anaconda3/envs/py37/lib/python3.7/site-packages
Searching for psutil==5.6.3
Best match: psutil 5.6.3
Adding psutil 5.6.3 to easy-install.pth file

Using /home/denis/anaconda3/envs/py37/lib/python3.7/site-packages
Finished processing dependencies for pg-activity==1.5.0


(py37) denis:~/gitdnwld/pg_activity $ pg_activity 
Traceback (most recent call last):
  File "/home/denis/anaconda3/envs/py37/bin/pg_activity", line 4, in <module>
    __import__('pkg_resources').run_script('pg-activity==1.5.0', 'pg_activity')
  File "/home/denis/anaconda3/envs/py37/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/denis/anaconda3/envs/py37/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/pg_activity' not found in metadata at '/home/denis/gitdnwld/pg_activity/pg_activity.egg-info'


(py37) denis:~/gitdnwld/pg_activity $ locate pg_activity
/home/denis/anaconda3/envs/py37/bin/pg_activity
/home/denis/anaconda3/envs/py37/lib/python3.7/site-packages/pg_activity-1.5.0-py3.7.egg


(py37) denis:~/gitdnwld/pg_activity $ pip show setuptools
Name: setuptools
Version: 41.0.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /home/denis/anaconda3/envs/py37/lib/python3.7/site-packages
Requires: 
Required-by: tldextract, kiwisolver

(py37) denis:~/gitdnwld/pg_activity $ which python
/home/denis/anaconda3/envs/py37/bin/python
```

**Comment by blogh** [comment]
Hi, do you have solved your problem ?
