### ISSUE TITLE
Unable to run, missing psycopg2

### ISSUE THREAD

**Issue by andrejohansson** [dalibo/pg_activity#131]
For whatever reason, I'm not able to run this. I get a crash about a missing ``psycopg2`` even though it´s clearly there.

This is on an Azure vm.

**Install psycopg2-binary**
```bash
rduceadmin@vmsynapse:~/pg_activity$ pip install  psycopg2-binary
Collecting psycopg2-binary
  Using cached https://files.pythonhosted.org/packages/97/2a/b854019bcb9b925cd10ff245dbc9448a82fe7fdb40127e5cf1733ad0765c/psycopg2_binary-2.8.4-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.8.4
```

**Ensure libpq-dev exists**
```bash
rduceadmin@vmsynapse:~/pg_activity$ sudo apt-get install libpq-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpq-dev is already the newest version (12.2-2.pgdg18.04+1).
The following packages were automatically installed and are no longer required:
  grub-pc-bin libdumbnet1 linux-azure-cloud-tools-5.0.0-1028 linux-azure-cloud-tools-5.0.0-1029 linux-azure-headers-5.0.0-1028 linux-azure-headers-5.0.0-1029 linux-azure-tools-5.0.0-1028 linux-azure-tools-5.0.0-1029
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
```

**Install psycopg2, just to be sure**
```bash
rduceadmin@vmsynapse:~/pg_activity$ pip install psycopg2
Collecting psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.8.4
```

**Install pg_activity**
```bash
rduceadmin@vmsynapse:~/pg_activity$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to pg_activity.egg-info/requires.txt
writing pg_activity.egg-info/PKG-INFO
writing top-level names to pg_activity.egg-info/top_level.txt
writing dependency_links to pg_activity.egg-info/dependency_links.txt
reading manifest file 'pg_activity.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 1: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'pg_activity.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pgactivity
copying build/lib.linux-x86_64-2.7/pgactivity/UI.py -> build/bdist.linux-x86_64/egg/pgactivity
copying build/lib.linux-x86_64-2.7/pgactivity/Data.py -> build/bdist.linux-x86_64/egg/pgactivity
copying build/lib.linux-x86_64-2.7/pgactivity/Process.py -> build/bdist.linux-x86_64/egg/pgactivity
copying build/lib.linux-x86_64-2.7/pgactivity/__init__.py -> build/bdist.linux-x86_64/egg/pgactivity
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/UI.py to UI.pyc
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/Data.py to Data.pyc
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/Process.py to Process.pyc
byte-compiling build/bdist.linux-x86_64/egg/pgactivity/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/pg_activity -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/pg_activity to 755
copying pg_activity.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pg_activity.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pg_activity-1.5.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pg_activity-1.5.0-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/pg_activity-1.5.0-py2.7.egg
Copying pg_activity-1.5.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
pg-activity 1.5.0 is already the active version in easy-install.pth
Installing pg_activity script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pg_activity-1.5.0-py2.7.egg
Processing dependencies for pg-activity==1.5.0
Searching for psutil==5.7.0
Best match: psutil 5.7.0
Processing psutil-5.7.0-py2.7-linux-x86_64.egg
psutil 5.7.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/psutil-5.7.0-py2.7-linux-x86_64.egg
Finished processing dependencies for pg-activity==1.5.0
```

**Try to run pg_activity, fails**

Lo and behold! It´s missing psycopg2! Ehh...but I just installed it.

```bash
rduceadmin@vmsynapse:~/pg_activity$ sudo -u postgres pg_activity -U postgres
Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 4, in <module>
    __import__('pkg_resources').run_script('pg-activity==1.5.0', 'pg_activity')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pg_activity-1.5.0-py2.7.egg/EGG-INFO/scripts/pg_activity", line 42, in <module>

ImportError: No module named psycopg2
```

**Test if psycopg2 exists**

```bash
rduceadmin@vmsynapse:~/pg_activity$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09)
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>>
```
No errors! So it does...or am I crazy?

**Some useful versions**

```bash
rduceadmin@vmsynapse:~/pg_activity$ python --version
Python 2.7.17

rduceadmin@vmsynapse:~$ /usr/lib/postgresql/12/bin/postgres --version
postgres (PostgreSQL) 12.2 (Ubuntu 12.2-2.pgdg18.04+1)
```

What am I doing wrong here? Feeling quite stupid...

**Comment by justinTM** [comment]
trying running the install with `python3`

**Comment by julmon** [comment]
> For whatever reason, I'm not able to run this. I get a crash about a missing `psycopg2` even though it´s clearly there.

[...]

> rduceadmin@vmsynapse:~/pg_activity$ pip install  psycopg2-binary

[...]

> What am I doing wrong here? Feeling quite stupid...

You should try to install `psycopg2` or `psycopg2-binary` with `sudo`  privileges because installing python packages with `pip` as a user won't make them available for all, they are installed in `/home/<user>/.local`

**Comment by andrejohansson** [comment]
@julmon was spot on, thank you! These commands fixed it for me:

```
# uninstall user-local version
sudo pip uninstall psycopg2-binary

# with sudo, install a system global version
sudo pip install psycopg2-binary

# run pg_activity
sudo -u postgres pg_activity -U postgres
```

Thank you!
