### ISSUE TITLE
v2.1.0 cannot find its queries

### ISSUE THREAD

**Issue by kmatt** [dalibo/pg_activity#190]
- pg_activity v2.1.0
- Python 3.9.2
- Fedora 33

```
Traceback (most recent call last):
  File "/home/me/.local/bin/pg_activity", line 321, in <module>
    ui.main(term, dataobj, host, options, dsn)
  File "/home/me/.local/lib/python3.9/site-packages/pgactivity/ui.py", line 164, in main
    active_connections = data.pg_get_active_connections()
  File "/home/me/.local/lib/python3.9/site-packages/pgactivity/data.py", line 291, in pg_get_active_connections
    query = queries.get("get_active_connections.sql")
  File "/home/me/.local/lib/python3.9/site-packages/pgactivity/queries/__init__.py", line 10, in get
    with path.open() as f:
  File "/usr/lib64/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.local/lib/python3.9/site-packages/pgactivity/queries/get_active_connections.sql.sql'
```

```
$ ls /home/me/.local/lib/python3.9/site-packages/pgactivity/queries/get_active_connections*
/home/me/.local/lib/python3.9/site-packages/pgactivity/queries/get_active_connections.sql
/home/me/.local/lib/python3.9/site-packages/pgactivity/queries/get_active_connections_post_90200.sql
```

**Comment by kmatt** [comment]
Issue does not seem to be present on v2.0.3

**Comment by dlax** [comment]
Thanks for the report.

A fix is in progress, and we'll release an new version today.

**Comment by dlax** [comment]
Version 2.1.1 is available on PyPI now.
