### ISSUE TITLE
Nicer error message  / workaround when the dbname is passed as an argument.

### ISSUE THREAD

**Issue by blogh** [dalibo/pg_activity#192]
The error is "normal", `postgres` is not a valid dsn.
In `psql`, using a database name as the argument of the program connects to the database.

Maybe we could do that or make a nicer error message.  

```
(pgactivity) [vagrant@pgluq pg_activity]$ pg_activity -h /tmp -U postgres postgres
Traceback (most recent call last):
  File "/home/vagrant/tmp/pgactivity/bin/pg_activity", line 306, in <module>
    min_duration=options.minduration,
  File "/home/vagrant/tmp/pgactivity/lib64/python3.6/site-packages/pgactivity/data.py", line 408, in pg_connect
    hide_queries_in_logs=options.hide_queries_in_logs,
  File "/home/vagrant/tmp/pgactivity/lib64/python3.6/site-packages/pgactivity/data.py", line 153, in pg_connect
    cursor_factory=psycopg2.extras.DictCursor,
  File "/home/vagrant/tmp/pgactivity/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/home/vagrant/tmp/pgactivity/lib64/python3.6/site-packages/psycopg2/extensions.py", line 167, in make_dsn
    tmp = parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: missing "=" after "postgres" in connection info string
```

**Comment by blogh** [comment]
Merged #195
