### ISSUE TITLE
2.1.3: test failures with python3.7

### ISSUE THREAD

**Issue by asarubbo** [dalibo/pg_activity#201]
I'm packaging 2.1.3 for gentoo and I hit the following:

```
python3.7 -m pytest -vv -ra
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/tmp/portage/dev-db/pg_activity-2.1.3/work/pg_activity-2.1.3, configfile: pytest.ini
collecting ... collected 44 items

pgactivity/activities.py::pgactivity.activities.sorted PASSED                                                                                                       [  2%]
pgactivity/activities.py::pgactivity.activities.update_max_iops PASSED                                                                                              [  4%]
pgactivity/data.py::pgactivity.data.Data.get_duration_column PASSED                                                                                                 [  6%]
pgactivity/data.py::pgactivity.data.pg_get_num_dev_version PASSED                                                                                                   [  9%]
pgactivity/data.py::pgactivity.data.pg_get_num_version PASSED                                                                                                       [ 11%]
pgactivity/handlers.py::pgactivity.handlers.duration_mode PASSED                                                                                                    [ 13%]
pgactivity/handlers.py::pgactivity.handlers.query_mode PASSED                                                                                                       [ 15%]
pgactivity/handlers.py::pgactivity.handlers.refresh_time PASSED                                                                                                     [ 18%]
pgactivity/handlers.py::pgactivity.handlers.sort_key_for PASSED                                                                                                     [ 20%]
pgactivity/handlers.py::pgactivity.handlers.verbose_mode PASSED                                                                                                     [ 22%]
pgactivity/keys.py::pgactivity.keys._sequence_by_int PASSED                                                                                                         [ 25%]
pgactivity/types.py::pgactivity.types.Column PASSED                                                                                                                 [ 27%]
pgactivity/types.py::pgactivity.types.Column._template_h_is_a_format_string_ PASSED                                                                                 [ 29%]
pgactivity/types.py::pgactivity.types.SelectableProcesses PASSED                                                                                                    [ 31%]
pgactivity/types.py::pgactivity.types.SystemInfo.default PASSED                                                                                                     [ 34%]
pgactivity/types.py::pgactivity.types.UI.column PASSED                                                                                                              [ 36%]
pgactivity/types.py::pgactivity.types.UI.columns PASSED                                                                                                             [ 38%]
pgactivity/types.py::pgactivity.types.UI.end_interactive PASSED                                                                                                     [ 40%]
pgactivity/types.py::pgactivity.types.UI.evolve PASSED                                                                                                              [ 43%]
pgactivity/types.py::pgactivity.types.UI.start_interactive PASSED                                                                                                   [ 45%]
pgactivity/types.py::pgactivity.types.UI.tick_interactive PASSED                                                                                                    [ 47%]
pgactivity/types.py::pgactivity.types.UI.toggle_pause PASSED                                                                                                        [ 50%]
pgactivity/types.py::pgactivity.types.enum_next PASSED                                                                                                              [ 52%]
pgactivity/utils.py::pgactivity.utils.MessagePile PASSED                                                                                                            [ 54%]
pgactivity/utils.py::pgactivity.utils.clean_str PASSED                                                                                                              [ 56%]
pgactivity/utils.py::pgactivity.utils.csv_write PASSED                                                                                                              [ 59%]
pgactivity/utils.py::pgactivity.utils.ellipsis PASSED                                                                                                               [ 61%]
pgactivity/utils.py::pgactivity.utils.format_duration PASSED                                                                                                        [ 63%]
pgactivity/utils.py::pgactivity.utils.get_duration PASSED                                                                                                           [ 65%]
pgactivity/utils.py::pgactivity.utils.short_state PASSED                                                                                                            [ 68%]
pgactivity/utils.py::pgactivity.utils.yn PASSED                                                                                                                     [ 70%]
pgactivity/views.py::pgactivity.views.format_query PASSED                                                                                                           [ 72%]
pgactivity/views.py::pgactivity.views.get_indent PASSED                                                                                                             [ 75%]
pgactivity/views.py::pgactivity.views.limit PASSED                                                                                                                  [ 77%]
pgactivity/views.py::pgactivity.views.query_mode FAILED                                                                                                             [ 79%]
pgactivity/views.py::pgactivity.views.shorten PASSED                                                                                                                [ 81%]
tests/test_activities.py::test_ps_complete PASSED                                                                                                                   [ 84%]
tests/test_activities.py::test_ps_complete_empty_procs PASSED                                                                                                       [ 86%]
tests/test_activities.py::test_mem_swap_load PASSED                                                                                                                 [ 88%]
tests/test_types.py::test_flag PASSED                                                                                                                               [ 90%]
tests/test_types.py::test_flag_from_options PASSED                                                                                                                  [ 93%]
tests/test_ui.txt::test_ui.txt FAILED                                                                                                                               [ 95%]
tests/test_views.txt::test_views.txt FAILED                                                                                                                         [ 97%]
tests/test_widgets.txt::test_widgets.txt FAILED                                                                                                                     [100%]

================================================================================ FAILURES =================================================================================
__________________________________________________________________ [doctest] pgactivity.views.query_mode __________________________________________________________________
157 Display query mode title.
158 
159     >>> from pgactivity.types import QueryMode, UI
160 
161     >>> term = Terminal()
162     >>> ui = UI.make(query_mode=QueryMode.blocking)
163     >>> query_mode(term, ui)
Expected:
                                    BLOCKING QUERIES
Got:
                                                                                 BLOCKING QUERIES

/var/tmp/portage/dev-db/pg_activity-2.1.3/work/pg_activity-2.1.3/pgactivity/views.py:163: DocTestFailure
__________________________________________________________________________ [doctest] test_ui.txt __________________________________________________________________________
005 >>> import optparse
006 >>> import time
007 >>> from unittest.mock import patch
008 
009 >>> import blessed
010 >>> from blessed.keyboard import Keystroke
011 
012 >>> from pgactivity import data, types, ui, widgets
013 
014 >>> postgres = getfixture("postgresql")
UNEXPECTED EXCEPTION: FixtureLookupError('postgresql', <FixtureRequest for <DoctestItem test_ui.txt>>)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 589, in _get_active_fixturedef
    return self._fixture_defs[argname]
KeyError: 'postgresql'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/doctest.py", line 1337, in __run
    compileflags, 1), test.globs)
  File "<doctest test_ui.txt[7]>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 581, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 592, in _get_active_fixturedef
    fixturedef = self._getnextfixturedef(argname)
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 473, in _getnextfixturedef
    raise FixtureLookupError(argname, self)
_pytest.fixtures.FixtureLookupError: ('postgresql', <FixtureRequest for <DoctestItem test_ui.txt>>)
/var/tmp/portage/dev-db/pg_activity-2.1.3/work/pg_activity-2.1.3/tests/test_ui.txt:14: UnexpectedException
________________________________________________________________________ [doctest] test_views.txt _________________________________________________________________________
001 >>> from blessed import Terminal
002 >>> from pgactivity.types import *
003 >>> from pgactivity.views import *
004 
005 >>> term = Terminal(force_styling=None)
006 >>> term.width
Expected:
    80
Got:
    171

/var/tmp/portage/dev-db/pg_activity-2.1.3/work/pg_activity-2.1.3/tests/test_views.txt:6: DocTestFailure
_______________________________________________________________________ [doctest] test_widgets.txt ________________________________________________________________________
008 
009 >>> print(widgets.boxed(term, "hello, world"), end="")
010 ┌──────────────┐
011 │ hello, world │
012 └──────────────┘
013 >>> print(widgets.boxed(term, "hello, world", border=False), end="")
014 <BLANKLINE>
015 hello, world
016 
017 >>> print(widgets.boxed(term, "hello, world", center=True), end="")
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
    -                                ┌──────────────┐                                
    -                                │ hello, world │                                
    -                                └──────────────┘                                
    +                                                                             ┌──────────────┐                                                                              
    +                                                                             │ hello, world │                                                                              
    +                                                                             └──────────────┘                                                                              

/var/tmp/portage/dev-db/pg_activity-2.1.3/work/pg_activity-2.1.3/tests/test_widgets.txt:17: DocTestFailure
========================================================================= short test summary info =========================================================================
FAILED pgactivity/views.py::pgactivity.views.query_mode
FAILED tests/test_ui.txt::test_ui.txt
FAILED tests/test_views.txt::test_views.txt
FAILED tests/test_widgets.txt::test_widgets.txt
====================================================================== 4 failed, 40 passed in 0.35s =======================================================================
```

**Comment by dlax** [comment]
Do you have `-s` or `--capture=no` option set in pytest's configuration? That would explain all failures but the one in `test_ui.txt`.

The problem with `test_ui.txt` is that `pytest-postgresql` plugin is missing; do you have this packaged in gentoo? Otherwise, I'd be open to remove this dependency if it helps packaging efforts.

**Comment by asarubbo** [comment]
> Do you have `-s` or `--capture=no` option set in pytest's configuration? That would explain all failures but the one in `test_ui.txt`.
> 
> The problem with `test_ui.txt` is that `pytest-postgresql` plugin is missing; do you have this packaged in gentoo? Otherwise, I'd be open to remove this dependency if it helps packaging efforts.

Hi,

I don't have -s and --capture=no

We don't have pytest-postgresql packaged here.

Can I do something else to help debug the issue?

**Comment by dlax** [comment]
Can you run pytest with '--capture=fd' and see if it resolves some issues?

**Comment by asarubbo** [comment]
> Can you run pytest with '--capture=fd' and see if it resolves some issues?

no, it doesn't solve the issue

**Comment by dlax** [comment]
Can you point me to a way to run a virtualized (or containerized) gentoo 
box so that I can try to reproduce myself?

**Comment by asarubbo** [comment]
setting the var COLUMNS="80"  seems to fix the issue.
