### ISSUE TITLE
Traceback Printed When User Sends Keyboard Interrupt (SIGINT)

### ISSUE THREAD

**Issue by vfrazao-ns1** [dalibo/pg_activity#209]
Great tool! This one thing has been bothering me - When I press ctrl+c the program will exit but also print a traceback - I pressed Ctrl+C with the intent to exit the program so I don't need the traceback information.

Steps to repro:

1. Start pg_activity
2. Run `pkill -2 pg_activity`
3. Observe results:

```
Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pgactivity/cli.py", line 293, in main
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/local/lib/python3.6/dist-packages/pgactivity/ui.py", line 236, in main
    key = term.inkey(timeout=ui.refresh_time) or None
  File "/usr/lib/python3/dist-packages/blessed/terminal.py", line 1126, in inkey
    while not ks and self.kbhit(timeout=_time_left(stime, timeout)):
  File "/usr/lib/python3/dist-packages/blessed/terminal.py", line 931, in kbhit
    ready_r, _, _ = select.select(check_r, [], [], timeout)
```

**Comment by dlax** [comment]
Fixed by #210, thanks again!
