### ISSUE TITLE
Traceback: Function pg_stat_get_wal_receiver() is currently not supported in Aurora

### ISSUE THREAD

**Issue by grutz** [dalibo/pg_activity#301]
Using `pg_activity 3.0.0a1` (commit 560070616458b606efd0c1d06166be0bec534ce9) against an AWS RDS/Aurora database, the following traceback occurs with `psycopg2-binary==2.9.3`

```
$ pg_activity -U <username> -h <host> -d <db> --rds --no-db-size

Traceback (most recent call last):
  File "/home/ubuntu/run2/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==3.0.0a1', 'console_scripts', 'pg_activity')()
  File "/home/ubuntu/run2/lib/python3.8/site-packages/pg_activity-3.0.0a1-py3.8.egg/pgactivity/cli.py", line 347, in main
    ui.main(term, dataobj, host, args)
  File "/home/ubuntu/run2/lib/python3.8/site-packages/pg_activity-3.0.0a1-py3.8.egg/pgactivity/ui.py", line 29, in main
    server_information = data.pg_get_server_information(
  File "/home/ubuntu/run2/lib/python3.8/site-packages/pg_activity-3.0.0a1-py3.8.egg/pgactivity/data.py", line 225, in pg_get_server_information
    cur.execute(
  File "/home/ubuntu/run2/lib/python3.8/site-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.FeatureNotSupported: Function pg_stat_get_wal_receiver() is currently not supported in Aurora
```

**Comment by blogh** [comment]
Thanks for the report, will look into it.

**Comment by blogh** [comment]
Hi,

Master should fix your problem. It disables wal receiver stats in case of failure or if you set "--no-walreceiver".
Feel free to reopen, in case it's still doesn't work.
