### ISSUE TITLE
ZeroDivisionError when server has no swap

### ISSUE THREAD

**Issue by iuridiniz** [dalibo/pg_activity#318]
Hello

**Description**
When the machine has no swap, the pg_activity does not open

**Software version:** 3.0.0

**Steps to reproduce:** 
Configure a machine with no swap, launch pg_activity

**Expected results:** 
pg_activity opens

**Actual results:** 
pg_acrivity crashes with `ZeroDivisionError: division by zero`

```
root@db1:~# pg_activity 

Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 8, in <module>
    sys.exit(main())
  File "/usr/local/pythonenv/pg_activity/lib/python3.7/site-packages/pgactivity/cli.py", line 407, in main
    ui.main(term, dataobj, host, args)
  File "/usr/local/pythonenv/pg_activity/lib/python3.7/site-packages/pgactivity/ui.py", line 250, in main
    width=width,
  File "/usr/local/pythonenv/pg_activity/lib/python3.7/site-packages/pgactivity/views.py", line 572, in screen
    width=width,
  File "/usr/local/pythonenv/pg_activity/lib/python3.7/site-packages/pgactivity/views.py", line 124, in wrapper
    for line in func(term, *args, **kwargs):
  File "/usr/local/pythonenv/pg_activity/lib/python3.7/site-packages/pgactivity/views.py", line 324, in header
    [f"{render(free)} ({render(system_info.swap.pct_free)}) free"],
  File "/usr/local/pythonenv/pg_activity/lib/python3.7/site-packages/pgactivity/types.py", line 704, in pct_free
    return Pct(self.free * 100 / self.total)
ZeroDivisionError: division by zero
root@db1:~# free
              total        used        free      shared  buff/cache   available
Mem:       32296672     6219592      571240      622296    25505840    25097340
Swap:             0           0           0
root@evoluxio-db1:~# 
```

**Comment by blogh** [comment]
thanks for reporting this !
