### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by smtspace** [dalibo/pg_activity#330]
pg_activity is getting  ModuleNotFoundError: No module named '_curses' error. Python 3.10.7 was compiled from source. No matter which pg_activity installation method is used, it's execution ends up with _curses module error.

Traceback (most recent call last):
  File "/var/lib/pgsql/pg_activity/.venv/bin/pg_activity", line 5, in <module>
    from pgactivity.cli import main
  File "/var/lib/pgsql/pg_activity/.venv/lib/python3.10/site-packages/pgactivity/cli.py", line 10, in <module>
    from blessed import Terminal
  File "/var/lib/pgsql/pg_activity/.venv/lib/python3.10/site-packages/blessed/__init__.py", line 14, in <module>
    from blessed.terminal import Terminal  # type: ignore
  File "/var/lib/pgsql/pg_activity/.venv/lib/python3.10/site-packages/blessed/terminal.py", line 21, in <module>
    from .keyboard import (_time_left,
  File "/var/lib/pgsql/pg_activity/.venv/lib/python3.10/site-packages/blessed/keyboard.py", line 19, in <module>
    import curses
  File "/usr/local/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

CentOS 7.9/RedHat 7.9
Python 3.10.7
pip3 22.3.1

Installed pip packages
Package         Version
--------------- -------
attrs           22.2.0
blessed         1.19.1
humanize        4.4.0
pg-activity     3.0.1
pip             22.3.1
psutil          5.9.4
psycopg2-binary 2.9.5
setuptools      63.2.0
six             1.16.0
wcwidth         0.2.5

Postgres version 13.9

**Comment by dlax** [comment]
> Python 3.10.7 was compiled from source.

Probably `libncurses-dev` was missing when you built Python, this can be seen in `config.log` file produced by `./configure` invocation (look for `checking for curses...` log lines).

That's unrelated to pg_activity, hence I'm closing this issue.
