### ISSUE TITLE
3.1.0 issue: AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by devrimgunduz** [dalibo/pg_activity#346]
Hi,

I'm trying to run pg_activity 3.1.0 (installed via RPMs) on Fedora 37 (Python 3.11, psycopg 3.1.8), and getting this. Any idea what am I missing?

Thanks!

>  $ pg_activity 
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 33, in <module>
    sys.exit(load_entry_point('pg-activity==3.1.0', 'console_scripts', 'pg_activity')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pgactivity/cli.py", line 388, in main
    dataobj = data.pg_connect(
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pgactivity/data.py", line 518, in pg_connect
    data = Data.pg_connect(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pgactivity/data.py", line 94, in pg_connect
    pg_conn = pg.connect(
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pgactivity/pg.py", line 45, in connect
    return psycopg.connect(*args, autocommit=True, row_factory=dict_row, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psycopg/connection.py", line 719, in connect
    params = cls._get_connection_params(conninfo, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psycopg/connection.py", line 778, in _get_connection_params
    params = conninfo_to_dict(conninfo, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psycopg/conninfo.py", line 79, in conninfo_to_dict
    opts = _parse_conninfo(conninfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psycopg/conninfo.py", line 96, in _parse_conninfo
    return pq.Conninfo.parse(conninfo.encode())
                             ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by dlax** [comment]
It looks like your psycopg package is not working fine. Can you try `python -c 'import psycopg; psycopg.connect()'` to confirm?

**Comment by dlax** [comment]
Hm, no, sorry; I read too fast, that's indeed something on our side. I'll take a closer look.

**Comment by dlax** [comment]
I released version 3.1.1 with a fix. Thank you!

**Comment by devrimgunduz** [comment]
3.1.1 works great, thanks!
