### ISSUE TITLE
3.1.1: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by esabol** [dalibo/pg_activity#348]
Hi. The `README.md` says Python 3.7 and above is supported? I'm using Python 3.8.5, but I'm getting the following error:
```
Traceback (most recent call last):
  File "/path/to/home/.local/bin/pg_activity", line 8, in <module>
    sys.exit(main())
  File "/path/to/home/.local/lib/python3.8/site-packages/pgactivity/cli.py", line 389, in main
    dataobj = data.pg_connect(
  File "/path/to/home/.local/lib/python3.8/site-packages/pgactivity/data.py", line 518, in pg_connect
    data = Data.pg_connect(
  File "/path/to/home/.local/lib/python3.8/site-packages/pgactivity/data.py", line 107, in pg_connect
    pg_version = pg_get_short_version(pg_get_version(pg_conn))
  File "/path/to/home/.local/lib/python3.8/site-packages/pgactivity/data.py", line 57, in pg_get_short_version
    res = re.match(
  File "/usr1/local/anaconda_py3/miniconda38/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object

> ~/.local/bin/pg_activity --version
pg_activity 3.1.1
> /usr1/local/anaconda_py3/miniconda38/bin/python3 --version
Python 3.8.5
```
I installed it using the command `python3 -m pip install "pg_activity[psycopg]" --user`.

Thanks,
Ed

**Comment by dlax** [comment]
That's strange, I cannot reproduce (tried to install miniconda, which is Python 3.8.16 at the moment).

Can you try to run this python session from `/usr1/local/anaconda_py3/miniconda38/bin/python3` and report back?
```python
>>> from pgactivity import pg
>>> pg.__version__
>>> conn = pg.connect()
>>> pg.fetchone(conn, "select version()")
```

**Comment by dlax** [comment]
Ok; then can you try?
```python
>>> import psycopg
>>> conn = psycopg.connect("<your connection string>")
>>> conn.execute("select version()").fetchone()
```

**Comment by esabol** [comment]
`(b'PostgreSQL 10.23 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit',)`

**Comment by esabol** [comment]
Using `.decode()` to convert the bytes to a string works just fine, also:
```
>>> conn.execute("select version()").fetchone()[0].decode()
'PostgreSQL 10.23 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit'
```

**Comment by esabol** [comment]
Any idea what? I've tried with `LANG=en_US.UTF-8` and `unsetenv`-ing `LANG`, and I get the same result.

**Comment by esabol** [comment]
Well, it seems to be a bug in psycopg:

https://github.com/psycopg/psycopg/issues/503

Looks like it was fixed on February 1 (https://github.com/psycopg/psycopg/pull/504), but hasn't been released yet.

**Comment by dlax** [comment]
Indeed; the client encoding is probably a good lead.

Can you try adding `client_encoding=utf-8` to your connection string?

On my side:
```python
>>> import psycopg
>>> conn = psycopg.connect("client_encoding=sql_ascii")
>>> conn.info.encoding
'ascii'
>>> conn.execute("select version()").fetchone()
(b'PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit',)
>>>
>>> conn = psycopg.connect()
>>> conn.info.encoding
'utf-8'
>>> conn.execute("select version()").fetchone()
('PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit',)
```

However, the fix in psycopg you mention would not resolve this particular issue as it does not apply to all executed statements but only to `TypeInfo.fetch()`. So I think we should catch this early on our side and ... do something.

**Comment by esabol** [comment]
Yes, appending `" client_encoding=utf-8"` to my connection string seems to work!
```
>>> import psychopg
>>> conn = psycopg.connect(host=myhost dbname=mydatabase user=postgres client_encoding=utf-8")
>>> conn.info.encoding
'utf-8'
>>> conn.execute("select version()").fetchone()
('PostgreSQL 10.23 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit',)
```

**Comment by esabol** [comment]
If I do that with pg_activity, I still get an error, unfortunately:
```
> ~/.local/bin/pg_activity "host=myhost dbname=mydatabase user=postgres client_encoding=utf-8"

Traceback (most recent call last):
  File "/path/to/.local/bin/pg_activity", line 8, in <module>
    sys.exit(main())
  File "/path/to/.local/lib/python3.8/site-packages/pgactivity/cli.py", line 408, in main
    ui.main(term, dataobj, host, args)
  File "/path/to/.local/lib/python3.8/site-packages/pgactivity/ui.py", line 204, in main
    pg_procs.set_items(data.pg_get_activities(ui.duration_mode))
  File "/path/to/.local/lib/python3.8/site-packages/pgactivity/data.py", line 413, in pg_get_activities
    return pg.fetchall(
  File "/path/to/.local/lib/python3.8/site-packages/pgactivity/pg.py", line 147, in fetchall
    return cur.execute(query, args, prepare=True).fetchall()
  File "/path/to/.local/lib/python3.8/site-packages/psycopg/cursor.py", line 851, in fetchall
    records = self._tx.load_rows(self._pos, self.pgresult.ntuples, self._make_row)
  File "psycopg_binary/_psycopg/transform.pyx", line 490, in psycopg_binary._psycopg.Transformer.load_rows
  File "/path/to/.local/lib/python3.8/site-packages/psycopg/rows.py", line 208, in kwargs_row__
    return func(**dict(zip(names, values)))  # type: ignore[arg-type]
  File "/path/to/.local/lib/python3.8/site-packages/pgactivity/types.py", line 933, in from_bytes
    kwargs[name] = value.decode(enc, errors="replace")
LookupError: unknown encoding: SQL_ASCII
```

**Comment by dlax** [comment]
> If I do that with pg_activity, I still get an error, unfortunately:

Yes, I noticed that on my side too yesterday; that's a broader issue. I'm working on a fix.

Thank you for your patience.

**Comment by dlax** [comment]
@esabol I've stack all pending changes in a branch `issue348` in our git repo; can you try to install pg_activity as `python3 -m pip install "git+https://github.com/dalibo/pg_activity@issue348"` and tell me how this works for you?

**Comment by esabol** [comment]
@dlax : It works! Thank you very much!

Unrelated (apologies): Not sure if this is an issue with my terminal or what, but there are blue `â` ("a" with caret) characters at the lines at the top, like this:
```
-/4 logical workers â
 -/8 parallel workers
   Other processes & info: 0/3 autovacuum workers â
 0/10 wal senders â
 0 wal receivers â
 -/10 repl. slots
```
What are those supposed to be? Is that how it's supposed to look?

Also, every ~5 seconds or so, a lot of text is printed to the screen, but then it vanishes so quickly that I can't read what it says. Is that to be expected?

**Comment by esabol** [comment]
> What terminal are you using?

$TERM is "screen". But if I detach from my screen, my $TERM is xterm-color, and I still get the blue `â ("a" with caret)` instead of the blue bullets/dots. Ultimately, I'm inside a macOS Terminal window.

I think the text that flashes and then disappears every ~5 seconds are warnings about the `ascii` encoding....
