### ISSUE TITLE
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bytea

### ISSUE THREAD

**Issue by bagafoot** [dalibo/pg_activity#355]
Hello,
I'm monitoring postgres with pg_activity but sometimes it stops work and throw this error on terminal. How to solve this?

```
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==2.3.1', 'console_scripts', 'pg_activity')()
  File "/usr/lib/python3.6/site-packages/pgactivity/cli.py", line 299, in main
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/lib/python3.6/site-packages/pgactivity/ui.py", line 196, in main
    pg_procs.set_items(data.pg_get_activities(ui.duration_mode))
  File "/usr/lib/python3.6/site-packages/pgactivity/data.py", line 265, in pg_get_activities
    "dbname_filter": self.filters.dbname,
  File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 146, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bytea
```
                                                 version
----------------------------------------------------------------------------------------------------------
 PostgreSQL 12.14 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16), 64-bit

python3-psycopg2-2.8.6-1.rhel8.x86_64

pg_activity 2.3.1

**Comment by dlax** [comment]
This got resolved in a later release (3.1 at least, preferably 3.2).

**Comment by bagafoot** [comment]
@dlax hello again,
try to update but getting error on both rhel7 and rocky 8, any idea?  

Error: Package: pg_activity-3.1.1-1.rhel7.noarch (pgdg-common)
           Requires: python3-attrs >= 18.1
Error: Package: pg_activity-3.1.1-1.rhel7.noarch (pgdg-common)
           Requires: python3-humanize >= 2.6.0
           Available: python36-humanize-0.5.1-8.el7.noarch (epel)
               python3-humanize = 0.5.1-8.el7

**Comment by dlax** [comment]
Yes, it's a known *packaging* problem, see #322 and https://redmine.postgresql.org/issues/7717. Nothing we can do here unfortunately.

I'd suggest to install with pip, at least until the above issue gets resolved.
