### ISSUE TITLE
erorr attrs!=21.1,>=17 on centos8

### ISSUE THREAD

**Issue by ujangja** [dalibo/pg_activity#363]
[root@pg1 ~]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

dnf install python3 python3-attrs python3-humanize python3-psutil python3-psycopg2

rpm -ivh https://rpmfind.net/linux/epel/8/Everything/x86_64/Packages/p/python3-wcwidth-0.2.5-3.el8.noarch.rpm
rpm -ivh https://rpmfind.net/linux/epel/8/Everything/x86_64/Packages/p/python3-blessed-1.19.1-1.el8.noarch.rpm
rpm -ivh https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-8.5-x86_64/pg_activity-2.3.1-1.rhel8.noarch.rpm 

[root@pg1 ~]# pg_activity
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'attrs!=21.1,>=17' distribution was not found and is required by pg-activity
[root@pg1 ~]# rpm -qa | grep attrs
python3-attrs-22.1.0-1.rhel8.noarch

**Comment by dlax** [comment]
That's a packaging problem from PGDG repository, please report this [there](https://redmine.postgresql.org/projects/pgrpms/) if the issue is not known already.

In the meantime, I'd recommend installing from `pip`.
