### ISSUE TITLE
AttributeError: module 'attr.validators' has no attribute 'gt'

### ISSUE THREAD

**Issue by pashagolub** [dalibo/pg_activity#376]
```
$ pip list | grep pg-activity
pg-activity            3.4.0

$ ~/.local/bin/pg_activity
Traceback (most recent call last):
  File "/home/pasha/.local/bin/pg_activity", line 5, in <module>
    from pgactivity.cli import main
  File "/home/pasha/.local/lib/python3.10/site-packages/pgactivity/cli.py", line 12, in <module>
    from . import __version__, data, types, ui
  File "/home/pasha/.local/lib/python3.10/site-packages/pgactivity/data.py", line 13, in <module>
    from .types import (
  File "/home/pasha/.local/lib/python3.10/site-packages/pgactivity/types.py", line 28, in <module>
    from .config import Configuration, Flag
  File "/home/pasha/.local/lib/python3.10/site-packages/pgactivity/config.py", line 162, in <module>
    class UISection:
  File "/home/pasha/.local/lib/python3.10/site-packages/pgactivity/config.py", line 165, in UISection
    default=None, validator=validators.optional(validators.gt(0))
AttributeError: module 'attr.validators' has no attribute 'gt'
```

**Comment by dlax** [comment]
Thank you for the report; this has just been fixed in version 3.4.1.
