### ISSUE TITLE
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bytea

### ISSUE THREAD

**Issue by levisman** [dalibo/pg_activity#392]
When running for several seconds, I'm receiving this error:

```
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==2.3.1', 'console_scripts', 'pg_activity')()
  File "/usr/lib/python3/dist-packages/pgactivity/cli.py", line 299, in main
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/lib/python3/dist-packages/pgactivity/ui.py", line 196, in main
    pg_procs.set_items(data.pg_get_activities(ui.duration_mode))
  File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 261, in pg_get_activities
    cur.execute(
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bytea
```

**Comment by levisman** [comment]
Got fixed in 3.1.0
