### ISSUE TITLE
ValueError after connected

### ISSUE THREAD

**Issue by ltning** [dalibo/pg_activity#393]
Upon successfully connecting to a database, and seeing the UI (but without data - it's "RUNNING QUERIES" for a brief moment), pg_activity exits with the following trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/pg_activity-3.9", line 33, in <module>
    sys.exit(load_entry_point('pg-activity==3.4.1', 'console_scripts', 'pg_activity')())
  File "/usr/local/lib/python3.9/site-packages/pgactivity/cli.py", line 413, in main
    ui.main(term, cfg, dataobj, host, args)
  File "/usr/local/lib/python3.9/site-packages/pgactivity/ui.py", line 210, in main
    local_pg_procs, io_read, io_write = activities.ps_complete(
  File "/usr/local/lib/python3.9/site-packages/pgactivity/activities.py", line 80, in ps_complete
    new_proc = sys_get_proc(pid)
  File "/usr/local/lib/python3.9/site-packages/pgactivity/activities.py", line 34, in sys_get_proc
    (
ValueError: not enough values to unpack (expected 6, got 4)
```

Python: 3.9.17
py_activity: 3.4.1
OS: FreeBSD 13.2
PG PY adapter: py39-psycopg2-2.9.6
PG: 13.11

**Comment by ltning** [comment]
Looks like the problem is in `io_counters()`:
https://psutil.readthedocs.io/en/latest/#psutil.Process.io_counters

`read_chars` and `write_chars` are Linux-specific, and not available on FreeBSD.

**Comment by dlax** [comment]
Fixed in master; thank you for the report.
