### ISSUE TITLE
 invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by lanaparadinha** [dalibo/pg_activity#427]
-bash-4.2$ pg_activity
Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pgactivity/cli.py", line 299, in main
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/local/lib/python3.6/site-packages/pgactivity/ui.py", line 196, in main
    pg_procs.set_items(data.pg_get_activities(ui.duration_mode))
  File "/usr/local/lib/python3.6/site-packages/pgactivity/data.py", line 265, in pg_get_activities
    "dbname_filter": self.filters.dbname,
  File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 146, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.CharacterNotInRepertoire: invalid byte sequence for encoding "UTF8": 0xed 0x7a 0x65

**Comment by blogh** [comment]
Hi,

Sorry for the delay,  which version of pg_activity are you using ?
Support for Python 3.6 was dropped in pg_activity 3.0.0 (2022-09-16).
Thoses errors should have been fixed in [pg_activity 3.2](https://github.com/dalibo/pg_activity/blob/master/CHANGELOG.md#fixed-7)

**Comment by blogh** [comment]
As I said, the problem was fixed in 3.2.
I'll close this, please reopen it if the problem persists after the upgrade.
